### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by emirsassan** [TokaPass/toka-server#2]
Will change default database in future theres 2 option that we can choose

- MySQL
- Postgres

**Comment by khushal786** [comment]
I guess Postgres is good as its open source and we can have changes if you need help let me know

**Comment by emirsassan** [comment]
will use postgres probably but first i will clear some of the janky code inside both backend and frontend and probably migrate to a monorepo in future

**Comment by emirsassan** [comment]
[784ef6d](https://github.com/TokaPass/toka-server/commit/784ef6d307bd73113a302160539d74870a2ce559) changed default database to postgresql from sqlite
